### PR TITLE
added rc feature, also fixed overridebranch.

### PR DESCRIPTION
**Pull request by catdawg**
Added -rc feature to the update command.

Now, if libraries have tags that are of type x.y.z-rc they will be considered if the update is done with "-rc". 

Example:
Library A:
- 1.1.0-rc
- 1.0.2
- 1.0.1
- 1.0.0

An update on this library requesting version 1.0.0+ with "duell update" would set the version 1.0.2.
An update with "duell update -rc" it would instead set version 1.1.0-rc.

If a library explicitly requests an rc version, it also works, regardless of the argument.

Later on, if we feel there is the need for it. We can expand this to also support -alpha and -beta that would work exactly the same way.

Thanks!

### CODE REVIEW

**Comment by nensanders** [comment]
Is it working with schema validation?

**Comment by fluffybird** [comment]
Yes, it’s my last commit.

**Comment by catdawg** [comment]
Yes, it’s my last commit.

**Comment by nensanders** [comment]
Checked and tested

**Pull request merged**
